services:
  backend:
    build: ./backend
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb+srv://fullstack:fullstack@cluster0.7h4xk.mongodb.net/blogs?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend